// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByripeDzywWWvXWwrrfEf12au-neuqk84',
    appId: '1:684639991464:web:f69715e1ee5b8eb2b3b49d',
    messagingSenderId: '684639991464',
    projectId: 'chat-now-9586a',
    authDomain: 'chat-now-9586a.firebaseapp.com',
    storageBucket: 'chat-now-9586a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA93gTOb1JCVOKUFb_VekUS2Ne91DkILmM',
    appId: '1:684639991464:android:1c8e315a1014f598b3b49d',
    messagingSenderId: '684639991464',
    projectId: 'chat-now-9586a',
    storageBucket: 'chat-now-9586a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo5lXeWKfmX3YvcqQiYGy2S9XHzyhHt4E',
    appId: '1:684639991464:ios:006819421d815be0b3b49d',
    messagingSenderId: '684639991464',
    projectId: 'chat-now-9586a',
    storageBucket: 'chat-now-9586a.appspot.com',
    iosClientId: '684639991464-ag7ku0734lqp11acijmcf0k0qdnksvjp.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatNow',
  );
}
